select * from mytable;

-- Q1. What is the structure of the dataset?
describe mytable;

-- Q2. How many records are present in the dataset
SELECT COUNT(*) AS row_count FROM mytable;

-- Q3. How many NULL values exist in key columns?
SELECT 
  SUM(customer_id IS NULL) AS customer_id_nulls,
  SUM(age IS NULL) AS age_nulls,
  SUM(gender IS NULL) AS gender_nulls,
  SUM(item_purchased IS NULL) AS item_nulls,
  SUM(category IS NULL) AS category_nulls,
  SUM(purchase_amount IS NULL) AS purchase_nulls
FROM mytable;

-- Q4. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from mytable
group by gender;

-- Q5. Which customers used discounts and still have total spend above the global average purchase?
WITH stats AS (
    SELECT AVG(purchase_amount) AS avg_purchase
    FROM mytable
),
cust_spend AS (
    SELECT customer_id,
           SUM(purchase_amount) AS total_discount_spend
    FROM mytable
    WHERE discount_applied = 'Yes'
    GROUP BY customer_id
)
SELECT c.customer_id, c.total_discount_spend
FROM cust_spend c
CROSS JOIN stats s
WHERE c.total_discount_spend > s.avg_purchase;

-- Q6. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, 
       ROUND(AVG(review_rating),2) AS Average_Product_Rating
FROM mytable
GROUP BY item_purchased
ORDER BY Average_Product_Rating DESC
LIMIT 5;

-- Q7. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from mytable
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q8. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM mytable
GROUP BY subscription_status
ORDER BY total_revenue DESC,avg_spend DESC;

-- Q9. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM mytable
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q10. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM mytable)
select customer_segment,count(*) AS Number_of_Customers
from customer_type 
group by customer_segment;

-- Q11. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM mytable
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
-- Q12. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q13. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue desc;

-- Q14. How many unique customers does the company have?
SELECT COUNT(DISTINCT customer_id) AS total_customers
FROM mytable;

-- Q15. What is the average purchase amount per customer?
SELECT AVG(total_spend) AS avg_spend_per_customer
FROM (
    SELECT customer_id,
           SUM(purchase_amount) AS total_spend
    FROM mytable
    GROUP BY customer_id
) t;

-- Q16. What is the average product rating across all purchases?
SELECT AVG(CAST(review_rating AS DECIMAL(3,2))) AS avg_rating FROM mytable
WHERE review_rating IS NOT NULL;

-- Q17. What does the demographic breakdown (gender, age group) look like?
SELECT gender, COUNT(*) AS cnt FROM mytable
GROUP BY gender;
-- Age group distribution
SELECT age_group, COUNT(*) AS cnt FROM mytable
GROUP BY age_group 
ORDER BY cnt DESC;

-- Q18. Which product categories generate the highest revenue?
SELECT category, SUM(CAST(purchase_amount AS DECIMAL(12,2))) AS revenue FROM mytable
GROUP BY category
ORDER BY revenue DESC;

-- Q19. Which seasons contribute most to total revenue?
SELECT season, SUM(CAST(purchase_amount AS DECIMAL(12,2))) AS revenue FROM mytable
GROUP BY season
ORDER BY revenue DESC;

-- Q20. Which items are purchased most frequently?
SELECT item_purchased, COUNT(*) AS total_orders
FROM mytable
GROUP BY item_purchased
ORDER BY total_orders DESC
LIMIT 10;

-- Q21. Does applying a discount increase or decrease the average purchase amount?
SELECT discount_applied,
       COUNT(*) AS orders,
       AVG(CAST(purchase_amount AS DECIMAL(12,2))) AS avg_spend,
       AVG(CAST(review_rating AS DECIMAL(3,2))) AS avg_rating
FROM mytable
GROUP BY discount_applied;

-- Q22. Are subscribers more valuable customers than non-subscribers?
SELECT subscription_status,
       AVG(CAST(purchase_amount AS DECIMAL(12,2))) AS avg_spend,
       AVG(CAST(frequency_of_purchases AS DECIMAL(10,2))) AS avg_freq,
       AVG(CAST(review_rating AS DECIMAL(3,2))) AS avg_review
FROM mytable
GROUP BY subscription_status;

-- Q23. How do different genders purchase across product categories?
SELECT gender, category, SUM(CAST(purchase_amount AS DECIMAL(12,2))) AS revenue FROM mytable
GROUP BY gender, category
ORDER BY gender, revenue DESC;

-- Q24. Which age group purchases the most or spends the most?
SELECT age_group, AVG(CAST(purchase_amount AS DECIMAL(12,2))) AS avg_spend FROM mytable
GROUP BY age_group
ORDER BY avg_spend DESC;

-- Q25. What is the spending and purchase frequency of each customer?
CREATE OR REPLACE VIEW sys.customer_agg AS
SELECT 
  customer_id,
  AVG(CAST(purchase_amount AS DECIMAL(12,2))) AS avg_spend,
  SUM(CAST(purchase_amount AS DECIMAL(12,2))) AS total_spend,
  MAX(CAST(frequency_of_purchases AS UNSIGNED)) AS purchase_freq,
  MAX(CAST(previous_purchases AS UNSIGNED)) AS prev_purchases,
  MAX(subscription_status) AS subscription_status,
  MAX(gender) AS gender,
  MAX(age_group) AS age_group
FROM mytable
GROUP BY customer_id;

-- Q26. Can customers be segmented into high, medium, and low-value groups based on purchase frequency?
SELECT
  customer_id,
  total_spend,
  purchase_freq,
  CASE
    WHEN purchase_freq >= 10 THEN 'High Value'
    WHEN purchase_freq BETWEEN 5 AND 9 THEN 'Medium Value'
    ELSE 'Low Value'
  END AS customer_segment
FROM customer_agg
ORDER BY total_spend DESC;

-- Q27. How effective are discounts across different product categories?
SELECT 
  category,
  discount_applied,
  AVG(CAST(purchase_amount AS DECIMAL(12,2))) AS avg_spend
FROM mytable
GROUP BY category, discount_applied
ORDER BY category, avg_spend DESC;

-- Q28. Which categories have the highest customer satisfaction ratings?
SELECT 
  category,
  AVG(CAST(review_rating AS DECIMAL(3,2))) AS avg_rating,
  AVG(CAST(purchase_amount AS DECIMAL(12,2))) AS avg_spend,
  AVG(discount_applied = 'Yes') * 100 AS pct_discount_orders
FROM mytable
GROUP BY category
ORDER BY avg_rating DESC;

-- Q29. Which payment methods are preferred by customers?
SELECT payment_method, COUNT(*) AS usage_count
FROM mytable
GROUP BY payment_method
ORDER BY usage_count DESC;


-- EXPORT
-- Example: create a table of category revenue
CREATE TABLE IF NOT EXISTS category_revenue AS
SELECT category, SUM(CAST(purchase_amount AS DECIMAL(12,2))) AS revenue
FROM mytable
GROUP BY category;

CREATE OR REPLACE VIEW sys.category_revenue AS
SELECT category, SUM(purchase_amount) AS revenue
FROM sys.mytable
GROUP BY category;


CREATE OR REPLACE VIEW customer_agg AS
SELECT 
  customer_id,
  SUM(purchase_amount) AS total_spend,
  COUNT(*) AS purchase_freq,
  MAX(previous_purchases) AS prev_purchases,
  MAX(subscription_status) AS subscription_status,
  MAX(gender) AS gender,
  MAX(age_group) AS age_group
FROM mytable
GROUP BY customer_id;